### ISSUE TITLE
wszystkie testy failed - dlaczego?

### ISSUE THREAD

**Issue by malgorzatagora** [malgorzatagora/Magiczne-Schody#21]
nawet jeśli w środku wstawię Assert::AreEqual(1,1), to i tak mam fail... czy czego znów brakuje w moim VS? :(

**Comment by PawelOwsikowski** [comment]
Zrób proszę commit i wyphnij zmiany to zobaczę

**Comment by PawelOwsikowski** [comment]
Jest już, nie zauważyłem :)

**Comment by PawelOwsikowski** [comment]
U mnie Twoje testy przechodzą (CircularBuffer_TEST::AddingElements i AddingElementsBuffNotFull)

**Comment by malgorzatagora** [comment]
czyli coś mam nie tak z VS :/
Paweł czy ja Cię obudziłam?

**Comment by PawelOwsikowski** [comment]
Twoje testy są OK a odpowiadając na pytanie to nie spałem jeszcze:)

**Comment by PawelOwsikowski** [comment]
sms

**Comment by PawelOwsikowski** [comment]
Rozwiązanie: zmiana architektury procesora w ustawieniach testów
